---
- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
  tags:
    - dnsmasq

- name: set appropriate hostname
  hostname: 
    name: "{{ hostname }}"
  tags:
    - dnsmasq

- name: update hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - dnsmasq

- name: ensure dnsmasq.d directory exists
  file:
    path: /etc/dnsmasq.d
    state: directory
  tags:
    - dnsmasq

- name: configure dnsmasq common
  template:
    src: etc/dnsmasq.d/10-common.conf
    dest: /etc/dnsmasq.d/10-common.conf
    mode: 755
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: configure dnsmasq hosts
  template:
    src: etc/dnsmasq.d/20-hosts.conf
    dest: /etc/dnsmasq.d/20-hosts.conf
    mode: 755
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: configure dnsmasq general dns servers
  template:
    src: etc/dnsmasq.d/90-general-dns.conf
    dest: /etc/dnsmasq.d/90-general-dns.conf
    mode: 755
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq

- meta: flush_handlers
