- hosts: terminal
  any_errors_fatal: true
  sudo: True
  roles:
    - users
    - common
    - dnsmasq
    - docker
{%- if vpn_enabled == 'True' %}
    - openvpn
{% endif %}

- hosts: deployment
  any_errors_fatal: true
  sudo: True
  roles:
    - users
    - common
    - dnsmasq
    - docker
    - consul
    - consul-template

- hosts: consul-servers

- hosts: zookeepers
  any_errors_fatal: true
  sudo: True
  roles:
    - zookeeper

- hosts: zookeepers
  any_errors_fatal: true
  sudo: True
  roles:
    - exhibitor


{% for role in roles -%}
- hosts: tag_role_{{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - mesos-slave_{{ grid_name }}_{{ role }}
{% endfor %}


- hosts: mesos-masters
  any_errors_fatal: true
  sudo: True
  roles:
    - mesos
    - marathon
    - aurora
#    - triceratops

- hosts: terminal
  any_errors_fatal: true
  sudo: True
  roles:
    - terminal
