- hosts: dcos_masters
  any_errors_fatal: true
  sudo: True
  roles:
    - users

- hosts: deployment

- hosts: role={{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - users
    - common
    - docker

- hosts: {{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - dcos
