---
aurora: false
aurora_scheduler_uri: "http://repo.elodina.s3.amazonaws.com/aurora-scheduler-0.12.0-1.el7.centos.aurora.x86_64.rpm"
aurora_executor_uri: "http://repo.elodina.s3.amazonaws.com/aurora-executor-0.12.0-1.el7.centos.aurora.x86_64.rpm"
aurora_tools_uri: "http://repo.elodina.s3.amazonaws.com/aurora-tools-0.12.0-1.el7.centos.aurora.x86_64.rpm"
aurora_zk_dns: "zookeeper.service.{{ consul_dc }}"
aurora_zk_port: 2181
aurora_zk_path: mesos
aurora_zk_connect: "zk://{{ aurora_zk_dns }}:{{ aurora_zk_port }}/{{ aurora_zk_path }}"
aurora_replicated_log_dir: "/var/lib/aurora/scheduler/db"