- hosts: dcos_masters
  any_errors_fatal: true
  sudo: True
  roles:
    - users

- hosts: deployment

- hosts: tag_role_{{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - users
    - common
    - docker

- hosts: consul-servers

- hosts: tag_role_{{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - dcos
