- hosts: terminal
  any_errors_fatal: true
  sudo: True
  roles:
    - users

- hosts: deployment

- hosts: {{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - users
    - common
    - dnsmasq
    - docker
    - consul
    - consul-template

- hosts: consul-servers

- hosts: {{ grid_name }}_{{ role }}
  any_errors_fatal: true
  sudo: True
  roles:
    - mesos-slave_{{ grid_name }}_{{ role }}
